{
 "title": "ETL Demo - Kubernetes",
 "tags": [
  "kubernetes",
  "etl-demo"
 ],
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "role",
    "query": "label_values(kube_pod_labels{namespace='$namespace'}, label_role)"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{namespace='$namespace', label_role=~'$role'}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Per-pod CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod CPU (mCores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mc" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace='$namespace', pod=~'$pod', container!='POD', image!=''}[5m])) * 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace='$namespace', pod=~'$pod', container!='POD', image!=''}) / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Aggregated view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Workers CPU (namespace) mCores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mc" } },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(container_cpu_usage_seconds_total{namespace='$namespace', pod=~'etl-worker.*', container!='POD', image!=''}[5m])) * 1000",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum by(role) (rate(container_cpu_usage_seconds_total{namespace='$namespace', pod=~'$pod', label_role=~'$role', container!='POD', image!=''}[5m])) * 1000",
     "legendFormat": "role={{role}}"
    }
   ]
  },
  {
   "title": "Workers Memory (namespace) MiB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "targets": [
    {
     "expr": "sum by(namespace) (container_memory_working_set_bytes{namespace='$namespace', pod=~'etl-worker.*', container!='POD', image!=''}) / 1024 / 1024",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum by(role) (container_memory_working_set_bytes{namespace='$namespace', pod=~'$pod', label_role=~'$role', container!='POD', image!=''}) / 1024 / 1024",
     "legendFormat": "role={{role}}"
    }
   ]
  }
 ]
}